name: "Get Linked Issue"
on:
  pull_request:
    types: [closed]

jobs:
  auto-move-related-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: 1natsu172/github-action-get-linked-issue@master
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        id: auto-move-related-issue_action
        with:
          # github_token: "${{ secrets.GITHUB_TOKEN }}"
          config: "card-assign.yml"
